/* Generated By:JJTree&JavaCC: Do not edit this line. MyNewGrammar.java */
package shihu;

public class MyNewGrammar/*@bgen(jjtree)*/implements MyNewGrammarTreeConstants, MyNewGrammarConstants {/*@bgen(jjtree)*/
  protected static JJTMyNewGrammarState jjtree = new JJTMyNewGrammarState();public static void main(String args []) throws ParseException
  {
    MyNewGrammar parser = new MyNewGrammar(System.in);
    while (true)
    {
      System.out.println("Reading from standard input...");
      try
      {
        SimpleNode rootNode = MyNewGrammar.one_line();
        rootNode.dump("");
      }
      catch (Exception e)
      {
        System.out.println("NOK.");
        System.out.println(e.getMessage());
        MyNewGrammar.ReInit(System.in);
      }
      catch (Error e)
      {
        System.out.println("Oops.");
        System.out.println(e.getMessage());
        break;
      }
    }
  }

  static final public SimpleNode one_line() throws ParseException {
 /*@bgen(jjtree) ROOT */
  SimpleNode jjtn000 = new SimpleNode(JJTROOT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 42:
        define();
        jj_consume_token(22);
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    {if (true) return jjtn000;}
        break;
      case SYMBOL:
        call();
        jj_consume_token(22);
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
        {if (true) return jjtn000;}
        break;
      case 40:
        let();
        jj_consume_token(22);
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    {if (true) return jjtn000;}
        break;
      case 23:
        jj_consume_token(23);
        branch();
        jj_consume_token(22);
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
        {if (true) return jjtn000;}
        break;
      case 29:
        loop();
        jj_consume_token(22);
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    {if (true) return jjtn000;}
        break;
      case 31:
        ret();
        jj_consume_token(22);
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    {if (true) return jjtn000;}
        break;
      case 32:
        boom();
        jj_consume_token(22);
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
        {if (true) return jjtn000;}
        break;
      case 33:
        comment();
        jj_consume_token(22);
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
        {if (true) return jjtn000;}
        break;
      case 35:
        foreach();
        jj_consume_token(22);
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
        {if (true) return jjtn000;}
        break;
      default:
        jj_la1[0] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
    throw new Error("Missing return statement in function");
  }

  static final public void body() throws ParseException {
 /*@bgen(jjtree) BODY */
  SimpleNode jjtn000 = new SimpleNode(JJTBODY);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      label_1:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 23:
        case 29:
        case 31:
        case 32:
        case 33:
        case 35:
        case 40:
        case 42:
          ;
          break;
        default:
          jj_la1[1] = jj_gen;
          break label_1;
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 23:
          jj_consume_token(23);
          branch();
          jj_consume_token(22);
          break;
        case 40:
          let();
          jj_consume_token(22);
          break;
        case 42:
          define();
          jj_consume_token(22);
          break;
        case 29:
          loop();
          jj_consume_token(22);
          break;
        case 31:
          ret();
          jj_consume_token(22);
          break;
        case 32:
          boom();
          jj_consume_token(22);
          break;
        case 33:
          comment();
          jj_consume_token(22);
          break;
        case 35:
          foreach();
          jj_consume_token(22);
          break;
        default:
          jj_la1[2] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
    } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
    }
  }

  static final public void call() throws ParseException {
 /*@bgen(jjtree) CALL */
  SimpleNode jjtn000 = new SimpleNode(JJTCALL);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
           SimpleNode jjtn001 = new SimpleNode(JJTSYMBOL);
           boolean jjtc001 = true;
           jjtree.openNodeScope(jjtn001);
      try {
        jj_consume_token(SYMBOL);
      } finally {
           if (jjtc001) {
             jjtree.closeNodeScope(jjtn001, true);
           }
      }
      jj_consume_token(24);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NUMBER:
      case SYMBOL:
      case CHARACTER:
      case FLOAT:
      case 24:
        term();
        break;
      default:
        jj_la1[3] = jj_gen;
        ;
      }
      label_2:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 25:
          ;
          break;
        default:
          jj_la1[4] = jj_gen;
          break label_2;
        }
        jj_consume_token(25);
        term();
      }
      jj_consume_token(C);
    } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
    } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
    }
  }

  static final public void branch() throws ParseException {
 /*@bgen(jjtree) BRANCH */
  SimpleNode jjtn000 = new SimpleNode(JJTBRANCH);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(24);
      expression();
      jj_consume_token(C);
      jj_consume_token(27);
      body();
      jj_consume_token(28);
    } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
    } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
    }
  }

  static final public void loop() throws ParseException {
 /*@bgen(jjtree) LOOP */
  SimpleNode jjtn000 = new SimpleNode(JJTLOOP);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(29);
      expression();
      jj_consume_token(30);
      body();
      jj_consume_token(28);
    } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
    } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
    }
  }

  static final public void ret() throws ParseException {
 /*@bgen(jjtree) RET */
  SimpleNode jjtn000 = new SimpleNode(JJTRET);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(31);
      term();
    } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
    } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
    }
  }

  static final public void boom() throws ParseException {
 /*@bgen(jjtree) BOOM */
  SimpleNode jjtn000 = new SimpleNode(JJTBOOM);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(32);
    } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
    }
  }

  static final public void comment() throws ParseException {
 /*@bgen(jjtree) comment */
  SimpleNode jjtn000 = new SimpleNode(JJTCOMMENT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(33);
      label_3:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case CHARACTER:
          ;
          break;
        default:
          jj_la1[5] = jj_gen;
          break label_3;
        }
        jj_consume_token(CHARACTER);
      }
      jj_consume_token(34);
    } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
    }
  }

  static final public void foreach() throws ParseException {
 /*@bgen(jjtree) #FOREACH( 3) */
  SimpleNode jjtn000 = new SimpleNode(JJTFOREACH);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(35);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 36:
            SimpleNode jjtn001 = new SimpleNode(JJTNUM);
            boolean jjtc001 = true;
            jjtree.openNodeScope(jjtn001);
        try {
          jj_consume_token(36);
        } finally {
            if (jjtc001) {
              jjtree.closeNodeScope(jjtn001, true);
            }
        }
        break;
      case 37:
            SimpleNode jjtn002 = new SimpleNode(JJTFLOAT);
            boolean jjtc002 = true;
            jjtree.openNodeScope(jjtn002);
        try {
          jj_consume_token(37);
        } finally {
            if (jjtc002) {
              jjtree.closeNodeScope(jjtn002, true);
            }
        }
        break;
      case 38:
            SimpleNode jjtn003 = new SimpleNode(JJTCHAR);
            boolean jjtc003 = true;
            jjtree.openNodeScope(jjtn003);
        try {
          jj_consume_token(38);
        } finally {
            if (jjtc003) {
              jjtree.closeNodeScope(jjtn003, true);
            }
        }
        break;
      case SYMBOL:
            SimpleNode jjtn004 = new SimpleNode(JJTSYMBOL);
            boolean jjtc004 = true;
            jjtree.openNodeScope(jjtn004);
        try {
          jj_consume_token(SYMBOL);
        } finally {
            if (jjtc004) {
              jjtree.closeNodeScope(jjtn004, true);
            }
        }
        break;
      default:
        jj_la1[6] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(39);
               SimpleNode jjtn005 = new SimpleNode(JJTSYMBOL);
               boolean jjtc005 = true;
               jjtree.openNodeScope(jjtn005);
      try {
        jj_consume_token(SYMBOL);
      } finally {
               if (jjtc005) {
                 jjtree.closeNodeScope(jjtn005, true);
               }
      }
      jj_consume_token(27);
      body();
      jj_consume_token(28);
    } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
    } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000,  3);
          }
    }
  }

  static final public void let() throws ParseException {
 /*@bgen(jjtree) LET */
  SimpleNode jjtn000 = new SimpleNode(JJTLET);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(40);
      variable();
      jj_consume_token(41);
      expression();
    } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
    } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
    }
  }

  static final public void define() throws ParseException {
 /*@bgen(jjtree) DEF */
  SimpleNode jjtn000 = new SimpleNode(JJTDEF);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(42);
                SimpleNode jjtn001 = new SimpleNode(JJTSYMBOL);
                boolean jjtc001 = true;
                jjtree.openNodeScope(jjtn001);
      try {
        jj_consume_token(SYMBOL);
      } finally {
                if (jjtc001) {
                  jjtree.closeNodeScope(jjtn001, true);
                }
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 24:
        jj_consume_token(24);
            SimpleNode jjtn009 = new SimpleNode(JJTPARAS);
            boolean jjtc009 = true;
            jjtree.openNodeScope(jjtn009);
        try {
          label_4:
          while (true) {
            switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
            case SYMBOL:
            case 36:
            case 37:
            case 38:
              ;
              break;
            default:
              jj_la1[7] = jj_gen;
              break label_4;
            }
                  SimpleNode jjtn008 = new SimpleNode(JJTPARA);
                  boolean jjtc008 = true;
                  jjtree.openNodeScope(jjtn008);
            try {
              switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
              case 36:
                          SimpleNode jjtn002 = new SimpleNode(JJTNUM);
                          boolean jjtc002 = true;
                          jjtree.openNodeScope(jjtn002);
                try {
                  jj_consume_token(36);
                } finally {
                          if (jjtc002) {
                            jjtree.closeNodeScope(jjtn002, true);
                          }
                }
                break;
              case 37:
                  SimpleNode jjtn003 = new SimpleNode(JJTFLOAT);
                  boolean jjtc003 = true;
                  jjtree.openNodeScope(jjtn003);
                try {
                  jj_consume_token(37);
                } finally {
                  if (jjtc003) {
                    jjtree.closeNodeScope(jjtn003, true);
                  }
                }
                break;
              case 38:
                  SimpleNode jjtn004 = new SimpleNode(JJTCHAR);
                  boolean jjtc004 = true;
                  jjtree.openNodeScope(jjtn004);
                try {
                  jj_consume_token(38);
                } finally {
                  if (jjtc004) {
                    jjtree.closeNodeScope(jjtn004, true);
                  }
                }
                break;
              case SYMBOL:
                  SimpleNode jjtn005 = new SimpleNode(JJTSYMBOL);
                  boolean jjtc005 = true;
                  jjtree.openNodeScope(jjtn005);
                try {
                  jj_consume_token(SYMBOL);
                } finally {
                  if (jjtc005) {
                    jjtree.closeNodeScope(jjtn005, true);
                  }
                }
                break;
              default:
                jj_la1[8] = jj_gen;
                jj_consume_token(-1);
                throw new ParseException();
              }
              switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
              case 43:
                  SimpleNode jjtn006 = new SimpleNode(JJTARRAY);
                  boolean jjtc006 = true;
                  jjtree.openNodeScope(jjtn006);
                try {
                  jj_consume_token(43);
                } finally {
                  if (jjtc006) {
                    jjtree.closeNodeScope(jjtn006, true);
                  }
                }
                break;
              default:
                jj_la1[9] = jj_gen;
                ;
              }
                  SimpleNode jjtn007 = new SimpleNode(JJTSYMBOL);
                  boolean jjtc007 = true;
                  jjtree.openNodeScope(jjtn007);
              try {
                jj_consume_token(SYMBOL);
              } finally {
                  if (jjtc007) {
                    jjtree.closeNodeScope(jjtn007, true);
                  }
              }
              if (jj_2_1(2147483647) && (getToken(2).kind==C)) {
                jj_consume_token(C);
                jj_consume_token(44);
              } else {
                ;
              }
              switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
              case 25:
                jj_consume_token(25);
                break;
              default:
                jj_la1[10] = jj_gen;
                ;
              }
            } finally {
                  if (jjtc008) {
                    jjtree.closeNodeScope(jjtn008, jjtree.nodeArity() > 1);
                  }
            }
          }
        } finally {
            if (jjtc009) {
              jjtree.closeNodeScope(jjtn009, jjtree.nodeArity() > 0);
            }
        }
        jj_consume_token(C);
        jj_consume_token(41);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 36:
                  SimpleNode jjtn010 = new SimpleNode(JJTNUM);
                  boolean jjtc010 = true;
                  jjtree.openNodeScope(jjtn010);
          try {
            jj_consume_token(36);
          } finally {
                  if (jjtc010) {
                    jjtree.closeNodeScope(jjtn010, true);
                  }
          }
          break;
        case 37:
              SimpleNode jjtn011 = new SimpleNode(JJTFLOAT);
              boolean jjtc011 = true;
              jjtree.openNodeScope(jjtn011);
          try {
            jj_consume_token(37);
          } finally {
              if (jjtc011) {
                jjtree.closeNodeScope(jjtn011, true);
              }
          }
          break;
        case 38:
              SimpleNode jjtn012 = new SimpleNode(JJTCHAR);
              boolean jjtc012 = true;
              jjtree.openNodeScope(jjtn012);
          try {
            jj_consume_token(38);
          } finally {
              if (jjtc012) {
                jjtree.closeNodeScope(jjtn012, true);
              }
          }
          break;
        case SYMBOL:
          SimpleNode jjtn013 = new SimpleNode(JJTSYMBOL);
          boolean jjtc013 = true;
          jjtree.openNodeScope(jjtn013);
          try {
            jj_consume_token(SYMBOL);
          } finally {
          if (jjtc013) {
            jjtree.closeNodeScope(jjtn013, true);
          }
          }
          break;
        default:
          jj_la1[11] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        jj_consume_token(27);
        body();
        jj_consume_token(28);
        break;
      case 41:
        jj_consume_token(41);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 36:
              SimpleNode jjtn014 = new SimpleNode(JJTNUM);
              boolean jjtc014 = true;
              jjtree.openNodeScope(jjtn014);
          try {
            jj_consume_token(36);
          } finally {
              if (jjtc014) {
                jjtree.closeNodeScope(jjtn014, true);
              }
          }
          break;
        case 37:
              SimpleNode jjtn015 = new SimpleNode(JJTFLOAT);
              boolean jjtc015 = true;
              jjtree.openNodeScope(jjtn015);
          try {
            jj_consume_token(37);
          } finally {
              if (jjtc015) {
                jjtree.closeNodeScope(jjtn015, true);
              }
          }
          break;
        case 38:
              SimpleNode jjtn016 = new SimpleNode(JJTCHAR);
              boolean jjtc016 = true;
              jjtree.openNodeScope(jjtn016);
          try {
            jj_consume_token(38);
          } finally {
              if (jjtc016) {
                jjtree.closeNodeScope(jjtn016, true);
              }
          }
          break;
        default:
          jj_la1[12] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 45:
          jj_consume_token(45);
          term();
                       SimpleNode jjtn017 = new SimpleNode(JJTARRAY);
                       boolean jjtc017 = true;
                       jjtree.openNodeScope(jjtn017);
          try {
            jj_consume_token(46);
          } finally {
                       if (jjtc017) {
                         jjtree.closeNodeScope(jjtn017,  1);
                       }
          }
          break;
        default:
          jj_la1[13] = jj_gen;
          ;
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 27:
          jj_consume_token(27);
          value();
          jj_consume_token(28);
          break;
        default:
          jj_la1[14] = jj_gen;
          ;
        }
        break;
      case 27:
        jj_consume_token(27);
            SimpleNode jjtn018 = new SimpleNode(JJTDEFS);
            boolean jjtc018 = true;
            jjtree.openNodeScope(jjtn018);
        try {
          label_5:
          while (true) {
            switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
            case 42:
              ;
              break;
            default:
              jj_la1[15] = jj_gen;
              break label_5;
            }
            define();
          }
        } catch (Throwable jjte018) {
            if (jjtc018) {
              jjtree.clearNodeScope(jjtn018);
              jjtc018 = false;
            } else {
              jjtree.popNode();
            }
            if (jjte018 instanceof RuntimeException) {
              {if (true) throw (RuntimeException)jjte018;}
            }
            if (jjte018 instanceof ParseException) {
              {if (true) throw (ParseException)jjte018;}
            }
            {if (true) throw (Error)jjte018;}
        } finally {
            if (jjtc018) {
              jjtree.closeNodeScope(jjtn018, jjtree.nodeArity() > 0);
            }
        }
                         SimpleNode jjtn019 = new SimpleNode(JJTOBJ);
                         boolean jjtc019 = true;
                         jjtree.openNodeScope(jjtn019);
        try {
          jj_consume_token(47);
        } finally {
                         if (jjtc019) {
                           jjtree.closeNodeScope(jjtn019, true);
                         }
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 48:
          jj_consume_token(48);
                    SimpleNode jjtn020 = new SimpleNode(JJTSYMBOL);
                    boolean jjtc020 = true;
                    jjtree.openNodeScope(jjtn020);
          try {
            jj_consume_token(SYMBOL);
          } finally {
                    if (jjtc020) {
                      jjtree.closeNodeScope(jjtn020, true);
                    }
          }
          break;
        default:
          jj_la1[16] = jj_gen;
          ;
        }
        break;
      default:
        jj_la1[17] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
    } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
    }
  }

  static final public void value() throws ParseException {
 /*@bgen(jjtree) value */
  SimpleNode jjtn000 = new SimpleNode(JJTVALUE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NUMBER:
          SimpleNode jjtn001 = new SimpleNode(JJTNUM);
          boolean jjtc001 = true;
          jjtree.openNodeScope(jjtn001);
        try {
          jj_consume_token(NUMBER);
        } finally {
          if (jjtc001) {
            jjtree.closeNodeScope(jjtn001, true);
          }
        }
        break;
      case FLOAT:
      SimpleNode jjtn002 = new SimpleNode(JJTFLOAT);
      boolean jjtc002 = true;
      jjtree.openNodeScope(jjtn002);
        try {
          jj_consume_token(FLOAT);
        } finally {
      if (jjtc002) {
        jjtree.closeNodeScope(jjtn002, true);
      }
        }
        break;
      case CHARACTER:
      SimpleNode jjtn003 = new SimpleNode(JJTCHAR);
      boolean jjtc003 = true;
      jjtree.openNodeScope(jjtn003);
        try {
          jj_consume_token(CHARACTER);
        } finally {
      if (jjtc003) {
        jjtree.closeNodeScope(jjtn003, true);
      }
        }
        break;
      case SYMBOL:
          SimpleNode jjtn004 = new SimpleNode(JJTSYMBOL);
          boolean jjtc004 = true;
          jjtree.openNodeScope(jjtn004);
        try {
          jj_consume_token(SYMBOL);
        } finally {
          if (jjtc004) {
            jjtree.closeNodeScope(jjtn004, true);
          }
        }
        break;
      default:
        jj_la1[18] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
    }
  }

  static final public void expression() throws ParseException {
 /*@bgen(jjtree) expre */
  SimpleNode jjtn000 = new SimpleNode(JJTEXPRE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      condition();
      label_6:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case AND:
        case NOT:
        case OR:
          ;
          break;
        default:
          jj_la1[19] = jj_gen;
          break label_6;
        }
        expression2();
      }
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void expression2() throws ParseException {
 /*@bgen(jjtree) expre2 */
  SimpleNode jjtn000 = new SimpleNode(JJTEXPRE2);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case AND:
            SimpleNode jjtn001 = new SimpleNode(JJTAND);
            boolean jjtc001 = true;
            jjtree.openNodeScope(jjtn001);
        try {
          jj_consume_token(AND);
        } finally {
            if (jjtc001) {
              jjtree.closeNodeScope(jjtn001, true);
            }
        }
        break;
      case NOT:
            SimpleNode jjtn002 = new SimpleNode(JJTNOT);
            boolean jjtc002 = true;
            jjtree.openNodeScope(jjtn002);
        try {
          jj_consume_token(NOT);
        } finally {
            if (jjtc002) {
              jjtree.closeNodeScope(jjtn002, true);
            }
        }
        break;
      case OR:
            SimpleNode jjtn003 = new SimpleNode(JJTOR);
            boolean jjtc003 = true;
            jjtree.openNodeScope(jjtn003);
        try {
          jj_consume_token(OR);
        } finally {
            if (jjtc003) {
              jjtree.closeNodeScope(jjtn003, true);
            }
        }
        break;
      default:
        jj_la1[20] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      condition();
    } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
    } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
    }
  }

  static final public void condition() throws ParseException {
 /*@bgen(jjtree) COND */
  SimpleNode jjtn000 = new SimpleNode(JJTCOND);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      term();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LESS:
      case LARGER:
      case EQUAL:
      case LE:
      case BE:
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case LESS:
                  SimpleNode jjtn001 = new SimpleNode(JJTLESS);
                  boolean jjtc001 = true;
                  jjtree.openNodeScope(jjtn001);
          try {
            jj_consume_token(LESS);
          } finally {
                  if (jjtc001) {
                    jjtree.closeNodeScope(jjtn001, true);
                  }
          }
          break;
        case LARGER:
                    SimpleNode jjtn002 = new SimpleNode(JJTLARGER);
                    boolean jjtc002 = true;
                    jjtree.openNodeScope(jjtn002);
          try {
            jj_consume_token(LARGER);
          } finally {
                    if (jjtc002) {
                      jjtree.closeNodeScope(jjtn002, true);
                    }
          }
          break;
        case EQUAL:
                    SimpleNode jjtn003 = new SimpleNode(JJTEQUAL);
                    boolean jjtc003 = true;
                    jjtree.openNodeScope(jjtn003);
          try {
            jj_consume_token(EQUAL);
          } finally {
                    if (jjtc003) {
                      jjtree.closeNodeScope(jjtn003, true);
                    }
          }
          break;
        case LE:
                    SimpleNode jjtn004 = new SimpleNode(JJTLE);
                    boolean jjtc004 = true;
                    jjtree.openNodeScope(jjtn004);
          try {
            jj_consume_token(LE);
          } finally {
                    if (jjtc004) {
                      jjtree.closeNodeScope(jjtn004, true);
                    }
          }
          break;
        case BE:
                    SimpleNode jjtn005 = new SimpleNode(JJTBE);
                    boolean jjtc005 = true;
                    jjtree.openNodeScope(jjtn005);
          try {
            jj_consume_token(BE);
          } finally {
                    if (jjtc005) {
                      jjtree.closeNodeScope(jjtn005, true);
                    }
          }
          break;
        default:
          jj_la1[21] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        term();
        break;
      default:
        jj_la1[22] = jj_gen;
        ;
      }
    } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
    } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
    }
  }

  static final public void term() throws ParseException {
 /*@bgen(jjtree) term */
  SimpleNode jjtn000 = new SimpleNode(JJTTERM);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      subterm();
      label_7:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case PLUS:
        case MINUS:
          ;
          break;
        default:
          jj_la1[23] = jj_gen;
          break label_7;
        }
        term2();
      }
    } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
    } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
    }
  }

  static final public void term2() throws ParseException {
 /*@bgen(jjtree) #term2( 2) */
  SimpleNode jjtn000 = new SimpleNode(JJTTERM2);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PLUS:
            SimpleNode jjtn001 = new SimpleNode(JJTPLUS);
            boolean jjtc001 = true;
            jjtree.openNodeScope(jjtn001);
        try {
          jj_consume_token(PLUS);
        } finally {
            if (jjtc001) {
              jjtree.closeNodeScope(jjtn001, true);
            }
        }
        break;
      case MINUS:
            SimpleNode jjtn002 = new SimpleNode(JJTMINUS);
            boolean jjtc002 = true;
            jjtree.openNodeScope(jjtn002);
        try {
          jj_consume_token(MINUS);
        } finally {
            if (jjtc002) {
              jjtree.closeNodeScope(jjtn002, true);
            }
        }
        break;
      default:
        jj_la1[24] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      subterm();
    } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
    } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000,  2);
          }
    }
  }

  static final public void subterm() throws ParseException {
 /*@bgen(jjtree) subterm */
  SimpleNode jjtn000 = new SimpleNode(JJTSUBTERM);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      atom();
      label_8:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case MULTIPLY:
        case DIVIDE:
          ;
          break;
        default:
          jj_la1[25] = jj_gen;
          break label_8;
        }
        subterm2();
      }
    } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
    } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
    }
  }

  static final public void subterm2() throws ParseException {
 /*@bgen(jjtree) #subterm2( 2) */
  SimpleNode jjtn000 = new SimpleNode(JJTSUBTERM2);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MULTIPLY:
            SimpleNode jjtn001 = new SimpleNode(JJTMULTIPLY);
            boolean jjtc001 = true;
            jjtree.openNodeScope(jjtn001);
        try {
          jj_consume_token(MULTIPLY);
        } finally {
            if (jjtc001) {
              jjtree.closeNodeScope(jjtn001, true);
            }
        }
        break;
      case DIVIDE:
            SimpleNode jjtn002 = new SimpleNode(JJTDIVIDE);
            boolean jjtc002 = true;
            jjtree.openNodeScope(jjtn002);
        try {
          jj_consume_token(DIVIDE);
        } finally {
            if (jjtc002) {
              jjtree.closeNodeScope(jjtn002, true);
            }
        }
        break;
      default:
        jj_la1[26] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      atom();
    } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
    } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000,  2);
          }
    }
  }

  static final public void atom() throws ParseException {
 /*@bgen(jjtree) atom */
  SimpleNode jjtn000 = new SimpleNode(JJTATOM);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NUMBER:
      case SYMBOL:
      case CHARACTER:
      case FLOAT:
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case NUMBER:
            SimpleNode jjtn001 = new SimpleNode(JJTNUM);
            boolean jjtc001 = true;
            jjtree.openNodeScope(jjtn001);
          try {
            jj_consume_token(NUMBER);
          } finally {
            if (jjtc001) {
              jjtree.closeNodeScope(jjtn001, true);
            }
          }
          break;
        case FLOAT:
            SimpleNode jjtn002 = new SimpleNode(JJTFLOAT);
            boolean jjtc002 = true;
            jjtree.openNodeScope(jjtn002);
          try {
            jj_consume_token(FLOAT);
          } finally {
            if (jjtc002) {
              jjtree.closeNodeScope(jjtn002, true);
            }
          }
          break;
        case CHARACTER:
            SimpleNode jjtn003 = new SimpleNode(JJTCHAR);
            boolean jjtc003 = true;
            jjtree.openNodeScope(jjtn003);
          try {
            jj_consume_token(CHARACTER);
          } finally {
            if (jjtc003) {
              jjtree.closeNodeScope(jjtn003, true);
            }
          }
          break;
        case SYMBOL:
          variable();
          break;
        default:
          jj_la1[27] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
      case 24:
        jj_consume_token(24);
        expression();
        jj_consume_token(C);
        break;
      default:
        jj_la1[28] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
    } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
    }
  }

  static final public void variable() throws ParseException {
 /*@bgen(jjtree) VAR */
  SimpleNode jjtn000 = new SimpleNode(JJTVAR);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
            SimpleNode jjtn001 = new SimpleNode(JJTSYMBOL);
            boolean jjtc001 = true;
            jjtree.openNodeScope(jjtn001);
      try {
        jj_consume_token(SYMBOL);
      } finally {
            if (jjtc001) {
              jjtree.closeNodeScope(jjtn001, true);
            }
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 45:
        jj_consume_token(45);
        term();
                     SimpleNode jjtn002 = new SimpleNode(JJTARRAY);
                     boolean jjtc002 = true;
                     jjtree.openNodeScope(jjtn002);
        try {
          jj_consume_token(46);
        } finally {
                     if (jjtc002) {
                       jjtree.closeNodeScope(jjtn002,  1);
                     }
        }
        break;
      default:
        jj_la1[29] = jj_gen;
        ;
      }
      label_9:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 49:
          ;
          break;
        default:
          jj_la1[30] = jj_gen;
          break label_9;
        }
        symbol2();
      }
    } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
    } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
    }
  }

//此处无法将数组读成一个整体！！
  static final public void symbol2() throws ParseException {
 /*@bgen(jjtree) pointer */
  SimpleNode jjtn000 = new SimpleNode(JJTPOINTER);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(49);
                SimpleNode jjtn001 = new SimpleNode(JJTSYMBOL);
                boolean jjtc001 = true;
                jjtree.openNodeScope(jjtn001);
      try {
        jj_consume_token(SYMBOL);
      } finally {
                if (jjtc001) {
                  jjtree.closeNodeScope(jjtn001, true);
                }
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 45:
        jj_consume_token(45);
        term();
                           SimpleNode jjtn002 = new SimpleNode(JJTARRAY);
                           boolean jjtc002 = true;
                           jjtree.openNodeScope(jjtn002);
        try {
          jj_consume_token(46);
        } finally {
                           if (jjtc002) {
                             jjtree.closeNodeScope(jjtn002,  1);
                           }
        }
        break;
      default:
        jj_la1[31] = jj_gen;
        ;
      }
    } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
    } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
    }
  }

  static private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  static private boolean jj_3_1() {
    if (jj_scan_token(25)) return true;
    return false;
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public MyNewGrammarTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private Token jj_scanpos, jj_lastpos;
  static private int jj_la;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[32];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0xa0880000,0xa0800000,0xa0800000,0x13a0000,0x2000000,0x100000,0x80000,0x80000,0x80000,0x0,0x2000000,0x80000,0x0,0x0,0x8000000,0x0,0x0,0x9000000,0x3a0000,0xe00,0xe00,0x1f000,0x1f000,0x60,0x60,0x180,0x180,0x3a0000,0x13a0000,0x0,0x0,0x0,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x50b,0x50b,0x50b,0x0,0x0,0x0,0x70,0x70,0x70,0x800,0x0,0x70,0x70,0x2000,0x0,0x400,0x10000,0x200,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x2000,0x20000,0x2000,};
   }
  static final private JJCalls[] jj_2_rtns = new JJCalls[1];
  static private boolean jj_rescan = false;
  static private int jj_gc = 0;

  /** Constructor with InputStream. */
  public MyNewGrammar(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public MyNewGrammar(java.io.InputStream stream, String encoding) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new MyNewGrammarTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 32; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 32; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public MyNewGrammar(java.io.Reader stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new MyNewGrammarTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 32; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 32; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public MyNewGrammar(MyNewGrammarTokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 32; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(MyNewGrammarTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 32; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  static private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  static final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  static private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;
  static private int[] jj_lasttokens = new int[100];
  static private int jj_endpos;

  static private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      jj_entries_loop: for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              continue jj_entries_loop;
            }
          }
          jj_expentries.add(jj_expentry);
          break jj_entries_loop;
        }
      }
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  static public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[50];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 32; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 50; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

  static private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 1; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  static private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
