/* Generated By:JavaCC: Do not edit this line. MyNewGrammarTreeConstants.java Version 5.0 */
package TreeGenerator;

public interface MyNewGrammarTreeConstants
{
  public int JJTROOT = 0;
  public int JJTBODY = 1;
  public int JJTCALL = 2;
  public int JJTSYMBOL = 3;
  public int JJTBRANCH = 4;
  public int JJTLOOP = 5;
  public int JJTRET = 6;
  public int JJTBOOM = 7;
  public int JJTCOMMENT = 8;
  public int JJTFOREACH = 9;
  public int JJTNUM = 10;
  public int JJTFLOAT = 11;
  public int JJTCHAR = 12;
  public int JJTLET = 13;
  public int JJTBULK = 14;
  public int JJTDEF = 15;
  public int JJTARRAY = 16;
  public int JJTPARA = 17;
  public int JJTPARAS = 18;
  public int JJTDEFS = 19;
  public int JJTOBJ = 20;
  public int JJTVOID = 21;
  public int JJTCHARACTER = 22;
  public int JJTEXPRE = 23;
  public int JJTAND = 24;
  public int JJTNOT = 25;
  public int JJTOR = 26;
  public int JJTCOND = 27;
  public int JJTLESS = 28;
  public int JJTLARGER = 29;
  public int JJTEQUAL = 30;
  public int JJTLE = 31;
  public int JJTBE = 32;
  public int JJTTERM = 33;
  public int JJTPLUS = 34;
  public int JJTMINUS = 35;
  public int JJTSUBTERM = 36;
  public int JJTMULTIPLY = 37;
  public int JJTDIVIDE = 38;
  public int JJTATOM = 39;
  public int JJTVAR = 40;
  public int JJTPOINTER = 41;


  public String[] jjtNodeName = {
    "ROOT",
    "BODY",
    "CALL",
    "SYMBOL",
    "BRANCH",
    "LOOP",
    "RET",
    "BOOM",
    "comment",
    "FOREACH",
    "NUM",
    "FLOAT",
    "CHAR",
    "LET",
    "BULK",
    "DEF",
    "ARRAY",
    "PARA",
    "PARAS",
    "DEFS",
    "OBJ",
    "void",
    "CHARACTER",
    "expre",
    "AND",
    "NOT",
    "OR",
    "COND",
    "LESS",
    "LARGER",
    "EQUAL",
    "LE",
    "BE",
    "term",
    "PLUS",
    "MINUS",
    "subterm",
    "MULTIPLY",
    "DIVIDE",
    "atom",
    "VAR",
    "pointer",
  };
}
/* JavaCC - OriginalChecksum=d6a8c6f3f8d71246ffbda88e6da194af (do not edit this line) */
