/* Generated By:JavaCC: Do not edit this line. MyNewGrammarTreeConstants.java Version 5.0 */
package TreeGenerator;

public interface MyNewGrammarTreeConstants
{
  public int JJTROOT = 0;
  public int JJTBODY = 1;
  public int JJTCALL = 2;
  public int JJTSYMBOL = 3;
  public int JJTBRANCH = 4;
  public int JJTLOOP = 5;
  public int JJTRET = 6;
  public int JJTBOOM = 7;
  public int JJTCOMMENT = 8;
  public int JJTFOREACH = 9;
  public int JJTLET = 10;
  public int JJTBULK = 11;
  public int JJTDEF = 12;
  public int JJTNUM = 13;
  public int JJTFLOAT = 14;
  public int JJTCHAR = 15;
  public int JJTARRAY = 16;
  public int JJTPARA = 17;
  public int JJTPARAS = 18;
  public int JJTDEFS = 19;
  public int JJTOBJ = 20;
  public int JJTVOID = 21;
  public int JJTEXPRE = 22;
  public int JJTAND = 23;
  public int JJTNOT = 24;
  public int JJTOR = 25;
  public int JJTCOND = 26;
  public int JJTLESS = 27;
  public int JJTLARGER = 28;
  public int JJTEQUAL = 29;
  public int JJTLE = 30;
  public int JJTBE = 31;
  public int JJTTERM = 32;
  public int JJTPLUS = 33;
  public int JJTMINUS = 34;
  public int JJTSUBTERM = 35;
  public int JJTMULTIPLY = 36;
  public int JJTDIVIDE = 37;
  public int JJTATOM = 38;
  public int JJTVAR = 39;
  public int JJTPOINTER = 40;


  public String[] jjtNodeName = {
    "ROOT",
    "BODY",
    "CALL",
    "SYMBOL",
    "BRANCH",
    "LOOP",
    "RET",
    "BOOM",
    "comment",
    "FOREACH",
    "LET",
    "BULK",
    "DEF",
    "NUM",
    "FLOAT",
    "CHAR",
    "ARRAY",
    "PARA",
    "PARAS",
    "DEFS",
    "OBJ",
    "void",
    "expre",
    "AND",
    "NOT",
    "OR",
    "COND",
    "LESS",
    "LARGER",
    "EQUAL",
    "LE",
    "BE",
    "term",
    "PLUS",
    "MINUS",
    "subterm",
    "MULTIPLY",
    "DIVIDE",
    "atom",
    "VAR",
    "pointer",
  };
}
/* JavaCC - OriginalChecksum=3ed6e284e7c655cd8f0f98d17f328c07 (do not edit this line) */
